Importando as Bibliotecas

In [1]:
import pandas as pd 
import numpy as np 
import plotly.express as px
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

warnings.filterwarnings('ignore')

df = pd.read_csv('cancermama.csv')

df.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
0    842302.0          1        17.99         10.38          122.80   
1    842517.0          1        20.57         17.77          132.90   
2  84300903.0          1        19.69         21.25          130.00   
3  84348301.0          1        11.42         20.38           77.58   
4  84358402.0          1        20.29         14.34          135.10   

   area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0     1001.0          0.11840          0.104341          0.3001   
1     1326.0          0.08474          0.078640          0.0869   
2     1203.0          0.10960          0.159900          0.1974   
3      386.1          0.09636          0.104341          0.2414   
4     1297.0          0.10030          0.132800          0.1980   

   concave points_mean  ...  texture_worst  perimeter_worst  area_worst  \
0              0.14710  ...          17.33           184.60      2019.0   
1              0.07017  ...          23.41           158.80      1956.0   
2              0.12790  ...          25.53           152.50      1709.0   
3              0.10520  ...          26.50            98.87       567.7   
4              0.10430  ...          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0          0.162200           0.665600           0.7119              0.114606   
1          0.123800           0.186600           0.2416              0.186000   
2          0.144400           0.424500           0.4504              0.243000   
3          0.132369           0.254265           0.6869              0.257500   
4          0.137400           0.205000           0.4000              0.162500   

   symmetry_worst  fractal_dimension_worst  Unnamed: 32  
0        0.460100                 0.118900          NaN  
1        0.275000                 0.089020          NaN  
2        0.361300                 0.087580          NaN  
3        0.290076                 0.083946          NaN  
4        0.236400                 0.076780          NaN  

[5 rows x 33 columns]

In [2]:
previsores = df.iloc[:, 2:33]
previsores = previsores.drop('Unnamed: 32',axis=1)
previsores

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99     10.380000          122.80     1001.0          0.11840   
1          20.57     17.770000          132.90     1326.0          0.08474   
2          19.69     21.250000          130.00     1203.0          0.10960   
3          11.42     20.380000           77.58      386.1          0.09636   
4          20.29     14.340000          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56     22.390000          142.00     1479.0          0.11100   
565        20.13     28.250000          131.20     1261.0          0.09780   
566        16.60     28.080000          108.30      858.1          0.08455   
567        20.60     19.289649          140.10     1265.0          0.11780   
568         7.76     24.540000           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0            0.104341        0.300100             0.147100       0.241900   
1            0.078640        0.086900             0.070170       0.181200   
2            0.159900        0.197400             0.127900       0.206900   
3            0.104341        0.241400             0.105200       0.181162   
4            0.132800        0.198000             0.104300       0.180900   
..                ...             ...                  ...            ...   
564          0.115900        0.243900             0.138900       0.172600   
565          0.103400        0.144000             0.097910       0.175200   
566          0.102300        0.092510             0.053020       0.159000   
567          0.104341        0.088799             0.048919       0.239700   
568          0.043620        0.000000             0.000000       0.158700   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                  0.078710  ...        25.380      17.330000   
1                  0.056670  ...        24.990      23.410000   
2                  0.059990  ...        23.570      25.530000   
3                  0.062798  ...        14.910      26.500000   
4                  0.058830  ...        22.540      16.670000   
..                      ...  ...           ...            ...   
564                0.056230  ...        25.450      26.400000   
565                0.055330  ...        23.690      38.250000   
566                0.056480  ...        18.980      34.120000   
567                0.070160  ...        25.740      25.677223   
568                0.058840  ...         9.456      30.370000   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0          0.162200           0.665600   
1             158.80      1956.0          0.123800           0.186600   
2             152.50      1709.0          0.144400           0.424500   
3              98.87       567.7          0.132369           0.254265   
4             152.20      1575.0          0.137400           0.205000   
..               ...         ...               ...                ...   
564           166.10      2027.0          0.141000           0.211300   
565           155.00      1731.0          0.116600           0.192200   
566           126.70      1124.0          0.113900           0.309400   
567           184.60      1821.0          0.165000           0.254265   
568            59.16       268.6          0.089960           0.064440   

     concavity_worst  concave points_worst  symmetry_worst  \
0           0.711900              0.114606        0.460100   
1           0.241600              0.186000        0.275000   
2           0.450400              0.243000        0.361300   
3           0.686900              0.257500        0.290076   
4           0.400000              0.162500        0.236400   
..               ...                   ...             ...   
564         0.410700              0.221600        0

In [3]:
Alvo = df.iloc[:,1]
Alvo

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [4]:
coluna = df.iloc[:,0]

In [5]:
previsores1 = pd.concat([coluna,previsores],axis=1)

In [6]:
previsores1

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302.0        17.99     10.380000          122.80     1001.0   
1      842517.0        20.57     17.770000          132.90     1326.0   
2    84300903.0        19.69     21.250000          130.00     1203.0   
3    84348301.0        11.42     20.380000           77.58      386.1   
4    84358402.0        20.29     14.340000          135.10     1297.0   
..          ...          ...           ...             ...        ...   
564    926424.0        21.56     22.390000          142.00     1479.0   
565    926682.0        20.13     28.250000          131.20     1261.0   
566    926954.0        16.60     28.080000          108.30      858.1   
567    927241.0        20.60     19.289649          140.10     1265.0   
568     92751.0         7.76     24.540000           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840          0.104341        0.300100             0.147100   
1            0.08474          0.078640        0.086900             0.070170   
2            0.10960          0.159900        0.197400             0.127900   
3            0.09636          0.104341        0.241400             0.105200   
4            0.10030          0.132800        0.198000             0.104300   
..               ...               ...             ...                  ...   
564          0.11100          0.115900        0.243900             0.138900   
565          0.09780          0.103400        0.144000             0.097910   
566          0.08455          0.102300        0.092510             0.053020   
567          0.11780          0.104341        0.088799             0.048919   
568          0.05263          0.043620        0.000000             0.000000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.241900  ...        25.380      17.330000           184.60   
1         0.181200  ...        24.990      23.410000           158.80   
2         0.206900  ...        23.570      25.530000           152.50   
3         0.181162  ...        14.910      26.500000            98.87   
4         0.180900  ...        22.540      16.670000           152.20   
..             ...  ...           ...            ...              ...   
564       0.172600  ...        25.450      26.400000           166.10   
565       0.175200  ...        23.690      38.250000           155.00   
566       0.159000  ...        18.980      34.120000           126.70   
567       0.239700  ...        25.740      25.677223           184.60   
568       0.158700  ...         9.456      30.370000            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0          0.162200           0.665600         0.711900   
1        1956.0          0.123800           0.186600         0.241600   
2        1709.0          0.144400           0.424500         0.450400   
3         567.7          0.132369           0.254265         0.686900   
4        1575.0          0.137400           0.205000         0.400000   
..          ...               ...                ...              ...   
564      2027.0          0.141000           0.211300         0.410700   
565      1731.0          0.116600           0.192200         0.321500   
566      1124.0          0.113900           0.309400         0.340300   
567      1821.0          0.165000           0.254265         0.272188   
568       268.6          0.089960           0.064440         0.000000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.114606        0.460100                 0.118900  
1                0.186000        0.275000                 0.089020  
2                0.243000        0.361300                 0.087580  
3                0.257500        0.290076                 0.083946  
4                0.162500        0.236400                 0.076780  
..                 

In [50]:
previsores1.corr()

id  radius_mean  texture_mean  perimeter_mean  \
id                       1.000000     0.071473      0.077021        0.072132   
radius_mean              0.071473     1.000000      0.309455        0.978038   
texture_mean             0.077021     0.309455      1.000000        0.319489   
perimeter_mean           0.072132     0.978038      0.319489        1.000000   
area_mean                0.066058     0.991878      0.315680        0.969142   
smoothness_mean          0.038619     0.149929      0.019908        0.177876   
compactness_mean         0.064074     0.422232      0.245886        0.469444   
concavity_mean           0.059665     0.616012      0.322380        0.658079   
concave points_mean      0.102145     0.744701      0.299225        0.782726   
symmetry_mean            0.053149     0.139410      0.103938        0.165883   
fractal_dimension_mean  -0.038696    -0.298833     -0.048078       -0.265501   
radius_se                0.054447     0.600797      0.322018        0.617491   
texture_se              -0.064064    -0.113018      0.388022       -0.114608   
perimeter_se             0.065701     0.583785      0.313175        0.597794   
area_se                  0.046871     0.717818      0.328068        0.734277   
smoothness_se           -0.061818    -0.274885      0.050587       -0.259140   
compactness_se           0.011965     0.199335      0.241486        0.249742   
concavity_se             0.023934     0.313200      0.275081        0.351667   
concave points_se        0.007245     0.408451      0.232732        0.440122   
symmetry_se             -0.075183    -0.214759     -0.011518       -0.202529   
fractal_dimension_se    -0.016678    -0.007291      0.138831        0.030882   
radius_worst             0.069960     0.929296      0.337159        0.938234   
texture_worst            0.038893     0.295258      0.877565        0.297879   
perimeter_worst          0.066640     0.920619      0.350300        0.933430   
area_worst               0.056884     0.915876      0.337201        0.913686   
smoothness_worst         0.014631     0.137356      0.095486        0.151215   
compactness_worst        0.059549     0.418799      0.260830        0.466352   
concavity_worst          0.052765     0.544340      0.328515        0.582874   
concave points_worst     0.093431     0.690152      0.293102        0.732485   
symmetry_worst           0.062984     0.183246      0.090466        0.204063   
fractal_dimension_worst -0.019025     0.055943      0.102590        0.097378   

                         area_mean  smoothness_mean  compactness_mean  \
id                        0.066058         0.038619          0.064074   
radius_mean               0.991878         0.149929          0.422232   
texture_mean              0.315680         0.019908          0.245886   
perimeter_mean            0.969142         0.177876          0.469444   
area_mean                 1.000000         0.151365          0.417412   
smoothness_mean           0.151365         1.000000          0.604484   
compactness_mean          0.417412         0.604484          1.000000   
concavity_mean            0.621909         0.466324          0.838280   
concave points_mean       0.745450         0.508829          0.759529   
symmetry_mean             0.144020         0.483985          0.521040   
fractal_dimension_mean   -0.285559         0.530976          0.459958   
radius_se                 0.631082         0.281540          0.491289   
texture_se               -0.089598         0.098875          0.012281   
perimeter_se              0.614209         0.292594          0.491814   
area_se                   0.738962         0.269334          0.479515   
smoothness_se            -0.238634         0.316313          0.094218   
compactness_se            0.201488         0.299900          0.719026   
concavity_se              0.317095         0.289052          0.666160   
concave points_se         0.408177         0.392797          0.677299   
symmetry_s

In [7]:
scaler = StandardScaler()
previsores_esc = scaler.fit_transform(previsores1)


In [8]:
previsores_esc

array([[-0.44788305,  1.30470502, -2.23106547, ...,  0.05441657,
         3.40029434,  2.41078849],
       [-0.44787546,  2.12768882, -0.32488137, ...,  1.21712325,
        -0.20007849,  0.42732925],
       [ 2.50116186,  1.84698117,  0.57275336, ...,  2.14541538,
         1.47853942,  0.33174085],
       ...,
       [-0.44489184,  0.86131453,  2.33449049, ...,  0.49728971,
        -1.2348696 , -0.29091135],
       [-0.4448817 ,  2.1372584 ,  0.06709831, ...,  0.05441657,
         2.40051496,  2.74933073],
       [-0.47436876, -1.95852142,  1.4213793 , ..., -1.81204054,
         0.03527813, -0.80934564]])

In [9]:
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores1,Alvo,test_size=0.2,random_state=0)

In [10]:
x_teste.shape

(114, 31)

In [11]:
x_treino.shape

(455, 31)

In [12]:
y_teste.shape

(114,)

In [13]:
y_treino.shape

(455,)

In [14]:
models = {'naive': GaussianNB(),
          'lda': LinearDiscriminantAnalysis(),
          'svc': SVC(kernel='rbf',random_state=2,C=1),
          'logistica': LogisticRegression(random_state=2,max_iter=700,penalty='l2',tol=0.0001,C=1,solver='saga'), 
          'knn': KNeighborsClassifier(n_neighbors=1,metric='minkowski',p=1),
          'arvore': DecisionTreeClassifier(criterion='gini',splitter='best',max_depth=5,random_state=1),
          'random':RandomForestClassifier(n_estimators=400,criterion='gini',max_depth=1,random_state=1),
          'xg': XGBClassifier(max_depth=2,learning_rate=0.05,n_estimators=400,objective='reg:logistic',random_state=1),

    }
class machine():    
    def __init__(self,models,x_teste,x_treino,y_teste,y_treino):
        self.models = models
        self.x_teste = x_teste
        self.x_treino = x_treino
        self.y_teste = y_teste
        self.y_treino = y_treino
        self.modelo_score = {}

    def modelos(self):    
        for nome, model in self.models.items():
            
            model.fit(self.x_treino,self.y_treino)
    
            resultado = model.score(self.x_teste, self.y_teste) * 100
    
            # Corrigindo o formato da string
            resultado1 = '{:.2f}%'.format(resultado)
    
            self.modelo_score[nome] = resultado1
    
        md = pd.DataFrame(self.modelo_score,index=['Acuracia'])    
        return md
    
    def previsao(self,modelo,x,y):
        previsor = modelo.predict(x)
        print('\nAcuracia: %.2f%%\n' % (accuracy_score(y,previsor)*100))
        print(f'Matrix: \n{confusion_matrix(y,previsor)}\n')
        print(classification_report(y,previsor))

    def validacao_cruzada(self,mod,base):
        kf  = KFold(n_splits=30,shuffle=True,random_state=5)
        resul = cross_val_score(mod,base,Alvo,cv=kf)
        print('Acurácia Média: %.2f%%' % (resul.mean()*100.0))

Machine = machine(models,x_teste,x_treino,y_teste,y_treino)
Machine.modelos()


naive     lda     svc logistica     knn  arvore  random      xg
Acuracia  76.32%  95.61%  58.77%    58.77%  79.82%  95.61%  94.74%  97.37%

Modelo Naive Bayes Teste

In [15]:
Machine.previsao(modelo=models['naive'],x=x_teste,y=y_teste)


Acuracia: 76.32%

Matrix: 
[[67  0]
 [27 20]]

              precision    recall  f1-score   support

           0       0.71      1.00      0.83        67
           1       1.00      0.43      0.60        47

    accuracy                           0.76       114
   macro avg       0.86      0.71      0.71       114
weighted avg       0.83      0.76      0.74       114



Modelo Neive Bayes treino

In [16]:
Machine.previsao(modelo=models['naive'],x=x_treino,y=y_treino)


Acuracia: 76.70%

Matrix: 
[[289   1]
 [105  60]]

              precision    recall  f1-score   support

           0       0.73      1.00      0.85       290
           1       0.98      0.36      0.53       165

    accuracy                           0.77       455
   macro avg       0.86      0.68      0.69       455
weighted avg       0.82      0.77      0.73       455



Modelo de validação cruzada naive bayes

In [17]:
Machine.validacao_cruzada(mod=models['naive'],base=previsores1)

Acurácia Média: 70.98%


In [18]:
Machine.previsao(modelo=models['lda'],x=x_teste,y=y_teste)


Acuracia: 95.61%

Matrix: 
[[67  0]
 [ 5 42]]

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        67
           1       1.00      0.89      0.94        47

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [19]:
Machine.previsao(modelo=models['lda'],x=x_treino,y=y_treino)


Acuracia: 96.48%

Matrix: 
[[288   2]
 [ 14 151]]

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       290
           1       0.99      0.92      0.95       165

    accuracy                           0.96       455
   macro avg       0.97      0.95      0.96       455
weighted avg       0.97      0.96      0.96       455



In [20]:
Machine.validacao_cruzada(mod=models['lda'],base=previsores1)

Acurácia Média: 95.06%


In [21]:
Machine.previsao(modelo=models['svc'],x=x_teste,y=y_teste)


Acuracia: 58.77%

Matrix: 
[[67  0]
 [47  0]]

              precision    recall  f1-score   support

           0       0.59      1.00      0.74        67
           1       0.00      0.00      0.00        47

    accuracy                           0.59       114
   macro avg       0.29      0.50      0.37       114
weighted avg       0.35      0.59      0.44       114



In [22]:
Machine.previsao(modelo=models['svc'],x=x_treino,y=y_treino)


Acuracia: 63.74%

Matrix: 
[[290   0]
 [165   0]]

              precision    recall  f1-score   support

           0       0.64      1.00      0.78       290
           1       0.00      0.00      0.00       165

    accuracy                           0.64       455
   macro avg       0.32      0.50      0.39       455
weighted avg       0.41      0.64      0.50       455



In [23]:
Machine.validacao_cruzada(mod=models['svc'],base=previsores1)

Acurácia Média: 62.72%


In [24]:
Machine.previsao(modelo=models['logistica'],x=x_teste,y=y_teste)


Acuracia: 58.77%

Matrix: 
[[67  0]
 [47  0]]

              precision    recall  f1-score   support

           0       0.59      1.00      0.74        67
           1       0.00      0.00      0.00        47

    accuracy                           0.59       114
   macro avg       0.29      0.50      0.37       114
weighted avg       0.35      0.59      0.44       114



In [25]:
Machine.previsao(modelo=models['logistica'],x=x_treino,y=y_treino)


Acuracia: 63.74%

Matrix: 
[[290   0]
 [165   0]]

              precision    recall  f1-score   support

           0       0.64      1.00      0.78       290
           1       0.00      0.00      0.00       165

    accuracy                           0.64       455
   macro avg       0.32      0.50      0.39       455
weighted avg       0.41      0.64      0.50       455



In [26]:
Machine.validacao_cruzada(mod=models['logistica'],base=previsores1)

Acurácia Média: 62.72%


In [27]:
Machine.previsao(modelo=models['knn'],x=x_teste,y=y_teste)


Acuracia: 79.82%

Matrix: 
[[59  8]
 [15 32]]

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        67
           1       0.80      0.68      0.74        47

    accuracy                           0.80       114
   macro avg       0.80      0.78      0.79       114
weighted avg       0.80      0.80      0.80       114



In [28]:
Machine.previsao(modelo=models['knn'],x=x_treino,y=y_treino)


Acuracia: 100.00%

Matrix: 
[[290   0]
 [  0 165]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       290
           1       1.00      1.00      1.00       165

    accuracy                           1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455



In [29]:
Machine.validacao_cruzada(mod=models['knn'],base=previsores1)

Acurácia Média: 85.38%


In [30]:
Machine.previsao(modelo=models['arvore'],x=x_teste,y=y_teste)


Acuracia: 95.61%

Matrix: 
[[64  3]
 [ 2 45]]

              precision    recall  f1-score   support

           0       0.97      0.96      0.96        67
           1       0.94      0.96      0.95        47

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114



In [31]:
Machine.previsao(modelo=models['arvore'],x=x_treino,y=y_treino)


Acuracia: 99.12%

Matrix: 
[[289   1]
 [  3 162]]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       290
           1       0.99      0.98      0.99       165

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455



In [32]:
Machine.validacao_cruzada(mod=models['arvore'],base=previsores1)

Acurácia Média: 95.06%


In [33]:
Machine.previsao(modelo=models['random'], x=x_teste,y=y_teste)


Acuracia: 94.74%

Matrix: 
[[63  4]
 [ 2 45]]

              precision    recall  f1-score   support

           0       0.97      0.94      0.95        67
           1       0.92      0.96      0.94        47

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114



In [34]:
Machine.previsao(modelo=models['random'], x=x_treino,y=y_treino)


Acuracia: 93.41%

Matrix: 
[[282   8]
 [ 22 143]]

              precision    recall  f1-score   support

           0       0.93      0.97      0.95       290
           1       0.95      0.87      0.91       165

    accuracy                           0.93       455
   macro avg       0.94      0.92      0.93       455
weighted avg       0.93      0.93      0.93       455



In [35]:
Machine.validacao_cruzada(mod=models['random'],base=previsores1)

Acurácia Média: 92.25%


In [36]:
Machine.previsao(modelo=models['svc'],x=x_teste,y=y_teste)


Acuracia: 58.77%

Matrix: 
[[67  0]
 [47  0]]

              precision    recall  f1-score   support

           0       0.59      1.00      0.74        67
           1       0.00      0.00      0.00        47

    accuracy                           0.59       114
   macro avg       0.29      0.50      0.37       114
weighted avg       0.35      0.59      0.44       114



In [37]:
Machine.previsao(modelo=models['svc'],x=x_treino,y=y_treino)


Acuracia: 63.74%

Matrix: 
[[290   0]
 [165   0]]

              precision    recall  f1-score   support

           0       0.64      1.00      0.78       290
           1       0.00      0.00      0.00       165

    accuracy                           0.64       455
   macro avg       0.32      0.50      0.39       455
weighted avg       0.41      0.64      0.50       455



In [38]:
Machine.validacao_cruzada(mod=models['svc'],base=previsores1)

Acurácia Média: 62.72%


In [39]:
Machine.previsao(modelo=models['xg'],x=x_teste,y=y_teste)


Acuracia: 97.37%

Matrix: 
[[65  2]
 [ 1 46]]

              precision    recall  f1-score   support

           0       0.98      0.97      0.98        67
           1       0.96      0.98      0.97        47

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [40]:
Machine.previsao(modelo=models['xg'],x=x_treino,y=y_treino)


Acuracia: 100.00%

Matrix: 
[[290   0]
 [  0 165]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       290
           1       1.00      1.00      1.00       165

    accuracy                           1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455



In [ ]:
Machine.validacao_cruzada(mod=models['xg'],base=previsores1)

In [42]:
paciente = np.array([842302.0,17.99,10.38,122.8,1001.0,0.1184,0.1043409841827767,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.114606223198594,0.4601,0.1189
])
paciente = paciente.reshape(1,-1)
paciente1 = np.array([8510426.0,13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259])
paciente1 = paciente1.reshape(1,-1)

In [43]:
xg =XGBClassifier(max_depth=2,learning_rate=0.05,n_estimators=400,objective='reg:logistic',random_state=1)
xg.fit(previsores1,Alvo)
Xg = xg.predict(paciente1)

if Xg[0] == 1:
    print('Tumor maligno')
else:
    print('Tumor benigno')



Tumor benigno
